CREATE TABLE IF NOT EXISTS itemgroup(
        id INTEGER PRIMARY KEY AUTO_INCREMENT,
        title VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS item(
       id      INTEGER PRIMARY KEY AUTO_INCREMENT,
       title   VARCHAR(100) NOT NULL UNIQUE,
       groupid INTEGER,

       FOREIGN KEY (groupid) REFERENCES itemgroup(id)
);

INSERT INTO ITEMGROUP(TITLE) values ( 'Computers' );
INSERT INTO ITEMGROUP(TITLE) values ( 'Phones' );
INSERT INTO ITEMGROUP(TITLE) values ( 'TVs' );

INSERT INTO ITEM(TITLE, GROUPID) values ('Apple', 1);
INSERT INTO ITEM(TITLE, GROUPID) values ('DELL', 1);
INSERT INTO ITEM(TITLE, GROUPID) values ('HTC', 2);
INSERT INTO ITEM(TITLE, GROUPID) values ('Nokia', 2);
INSERT INTO ITEM(TITLE, GROUPID) values ('LG', 3);

SELECT ID, TITLE, GROUPID, ITEMGROUP.TITLE FROM item JOIN itemgroup ON ITEM.GROUPID = ITEMGROUP.ID WHERE ITEM.GROUPID = 2

DROP TABLE ITEMGROUP;
DROP TABLE ITEM;

